CampusHub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('user.urls')),
    path('', include('forum.urls')),
    path('verify/', include('django_email_verification.urls')),

]

forum/urls.py
from django.urls import path
from . import views

app_name = "forum"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path('posts/search', views.PostSearchView.as_view(), name='post_search'),
    path("<str:username>/profile", views.ProfileView.as_view(), name='profile'),
    path("admin-panel", views.AdminPanel.as_view(), name='admin_panel'),
    path('change-password/', views.CustomPasswordChangeView.as_view(), name='change_password'),
    path("new-post", views.CreatePostView.as_view(), name="create_post"),
    path('post/edit/<int:post_id>/', views.EditPostView.as_view(), name='edit_post'),
    path("new-poll", views.CreatePostWithPollView.as_view(), name='create_poll'),
    
    path("vote/<int:post_id>/<int:poll_id>", views.Vote.as_view(), name='poll_vote'),
    path("post/<int:pk>", views.PostDetailView.as_view(), name='post_detail'),
    path("community/<int:community_id>", views.CommunityView.as_view(), name='community_page'),
    path('post/like/<int:post_id>', views.LikePostView.as_view(), name='like-post'),
    path("post/comment/<int:post_id>", views.PostCommentView.as_view(), name='post_comment'),
    path("post/comment/<int:comment_id>/reply", views.PostReplyView.as_view(), name='post_reply'),
    path('comment/<int:comment_id>/like/', views.LikeCommentView.as_view(), name='like_comment'),
    path('delete-post/<int:post_id>', views.DeletePost.as_view(), name='delete_post'),
    path('disregard-post/<int:post_id>', views.DisregardReports.as_view(), name='disregard_reports'),
    path("report-post/<int:post_id>/", views.ReportPost.as_view(), name="report_post"),
    path("reports/<int:post_id>", views.ViewReports.as_view(), name='view_reports'),
    # path('poll/edit/<int:post_id>/', views.UpdatePostWithPollView.as_view(), name='edit_poll'),
    path('poll/edit/<int:post_id>/', views.UpdatePostWithPollView.as_view(), name='edit_poll'),
    path('comments/edit/<int:comment_id>/', views.EditComment.as_view(), name='edit_comment'),

    path('replies/edit/<int:reply_id>/', views.EditReply.as_view(), name='edit_reply'),
    
    path('comments/delete/<int:comment_id>/', views.DeleteComment.as_view(), name='delete_comment'),

    path('replies/delete/<int:reply_id>/', views.DeleteCommentReplyView.as_view(), name='delete_reply'),
    path('notifications/all/', views.all_notifications, name='all_notifications'),
    path('notifications/mark-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('guidelines/', views.community_guidelines, name='community_guidelines'),
]

user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from CampusHub import settings
from django.views.generic import TemplateView

app_name = "user"


urlpatterns = [
    # path("", views.HomePageView.as_view(), name="home"),
    path("sign-up", views.SignUpView.as_view(), name="sign-up"),
    # path("sign-in", LoginView.as_view(template_name="sign-in.html",
    #      next_page=reverse_lazy('forum:home')), name="sign-in"),
    path("sign-in", views.CustomLoginView.as_view(), name="sign-in"),
    path(
        "logout",
        LogoutView.as_view(next_page=reverse_lazy('user:sign-in')),
        name="logout",
    ),
    path("verification-sent", views.VerificationSentView.as_view(),
         name="verification-sent"),
    path('password/reset', views.ForgotPasswordView.as_view(), name='password_reset'),
    path('password/reset-done', TemplateView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('password/reset-email-sent', TemplateView.as_view(template_name='password/email_sent.html'), name='email-sent'),
    path('onboarding', views.onboarding_view, name='onboarding'),
]

forum/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpRequest
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView

from django.db import transaction, models
from datetime import timedelta
from django.utils import timezone

from .models import Notification
from .models import PostCommunity, Post, PostComment, PostCategory, PostLikes, PostCommentReply, CommentLike, Poll, PollChoice, PollVote, Report
from .forms import PostForm, PostCommentForm, PostCommentReplyForm, UpdateProfileForm, CustomPasswordChangeForm, PollChoiceFormSet

from django.contrib.auth import update_session_auth_hash
from .helpers import ask_assistant, moderate_post, moderate_img
from user.models import CustomUser
from django.db.models import Q, Count, F, Sum
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

def community_guidelines(request:HttpRequest):
    
    if request.user.is_authenticated:
        
        return render(request, 'forum/community/guidelines.html')
    else:
        return redirect(reverse_lazy('user:sign-in'))


def mark_notification_as_read(request, notification_id):
    if request.user.is_authenticated:
        try:
            notification = Notification.objects.get(id=notification_id, recipient=request.user)
            notification.is_read = True
            notification.save()
            return JsonResponse({'success': True})
        except Notification.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Notification not found'}, status=404)
    return JsonResponse({'success': False, 'error': 'User not authenticated'}, status=401)


@login_required
def all_notifications(request):
    notifications = Notification.objects.filter(recipient=request.user).order_by('-timestamp')
    return render(request, 'forum/notifications/all_notifications.html', {'notifications': notifications})


class HomePageView(LoginRequiredMixin, View):

    template_name = "forum/home/home-v2.html"

    def get(self, request: HttpRequest):

        if request.user.is_authenticated:

            communities = PostCommunity.objects.all().order_by('community_name')
            all_posts = Post.objects.all().order_by("-time_created")

            seven_days_ago = timezone.now() - timedelta(days=7)
            latest_posts = Post.objects.filter(
                time_created__gte=seven_days_ago)

            # Latest Posts with like and comment count
            latest_posts_with_like_status_and_comments = []

            for post in latest_posts:
                # Using the related name 'likes'
                like_count = post.likes.filter(is_liked=True).count()
                comment_count = post.comments.count()  # Using the related name 'comments'

                latest_posts_with_like_status_and_comments.append({
                    'post': post,
                    'total_likes': like_count,
                    'total_comments': comment_count
                })

            # Fetch trending posts for the last 10 days
            ten_days_ago = timezone.now() - timedelta(days=10)
            trending_posts = (
                Post.objects.filter(time_created__gte=ten_days_ago)
                .annotate(total_interactions=Count('likes', filter=F('likes__is_liked')) + Count('comments'))
                # Top 10 posts by total interactions
                .order_by('-total_interactions')[:10]
            )

            trending_posts_with_data = []
            for post in trending_posts:
                trending_posts_with_data.append({
                    'post': post,
                    'total_interactions': post.total_interactions,
                    'total_likes': post.likes.filter(is_liked=True).count(),
                    'total_comments': post.comments.count(),
                })

            # Create a list of posts with their like status for the main feed (Current user)
            posts_with_like_status = []
            for post in all_posts:

                is_liked_by_user = PostLikes.objects.filter(
                    post=post, user=request.user, is_liked=True).exists()

                post_data = {
                    'post': post,
                    'is_liked_by_user': is_liked_by_user,
                    'total_comments': post.comments.count(),
                }
                # Check if the post contains a poll and add total votes
                poll = Poll.objects.filter(post=post).first()  # Use `filter` to safely check
                if poll:
                    total_votes = PollVote.objects.filter(poll=poll).count()
                    print(f"{poll} with votes {total_votes}")
                    post_data['total_votes'] = total_votes
                else:
                    print("No poll for this post")
                    
                posts_with_like_status.append(post_data)

            return render(request, self.template_name, {
                'posts_with_like_status': posts_with_like_status,
                'latest_posts_with_status': latest_posts_with_like_status_and_comments,
                'trending_posts_with_data': trending_posts_with_data,
                'communities': communities,
            })

        else:
            return redirect(reverse_lazy('user:sign-in'))


class PostSearchView(LoginRequiredMixin,View):

    template_name = 'forum/post/post-search.html'

    def get(self, request):

        communities = PostCommunity.objects.all().order_by('community_name')
        posts = Post.objects.all().order_by("-time_created")

        # Create a list of posts with their like status (Current user)
        posts_with_like_status = []

        query = request.GET.get('q')

        if query:
            # Filter posts by checking if the query is in the title or body
            posts = posts.filter(
                Q(title__icontains=query) | Q(body__icontains=query)
            )

        for post in posts:

            is_liked_by_user = PostLikes.objects.filter(
                post=post, user=request.user, is_liked=True).exists()
            posts_with_like_status.append({
                'post': post,
                'is_liked_by_user': is_liked_by_user,
                'total_comments': post.comments.count()
            })

        return render(request, self.template_name, {
            'posts_with_like_status': posts_with_like_status,
            'communities': communities,
            'query': query
        })


class CreatePostView(LoginRequiredMixin, View):

    template_name = "forum/post/create-post.html"

    def post(self, request: HttpRequest):

        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            community = form.cleaned_data.get('community')
            title = form.cleaned_data.get('title')
            body = form.cleaned_data.get('body')
            image = form.cleaned_data.get('image')

            post_category = PostCommunity.objects.get(community_name=community)
            author = request.user

            # Check if the user is suspended
            if author.is_suspended and author.suspension_end_date:
                if timezone.now() < author.suspension_end_date:
                    messages.error(
                        request,
                        f"Your account is suspended until {author.suspension_end_date.strftime(
                            '%Y-%m-%d %H:%M:%S')}. You cannot create new posts."
                    )
                    return redirect('forum:home')
                else:
                    # Suspension period is over
                    author.is_suspended = False
                    author.suspension_end_date = None
                    author.save()

            # Format content for moderation
            content = f'{title}\n\n{body}'

            final_action, actions = moderate_post(post_content=content)

            # Create the post instance but do not save yet
            post = form.save(commit=False)
            post.community = post_category

            # Image Moderation
            image_final_action = 'Accepted'
            image_nsfw_score = None

            if image:

                image_nsfw_score = moderate_img(image)
                print(f"nsfw_score: {image_nsfw_score}")

                if image_nsfw_score >= 0.5 and image_nsfw_score <= 0.6:

                    image_final_action = 'Warning Issued'
                    author.warning_count += 1
                    author.save()
                    post.image = image
                    messages.warning(
                        request,
                        f"Your post was rejected due to violating our community guidelines. Your account has been suspended until {
                            author.suspension_end_date.strftime('%Y-%m-%d %H:%M:%S')}."
                    )

                elif image_nsfw_score > 0.6:

                    image_final_action = 'Rejected'

            post.author = author
            post.moderation_status = final_action
            post.moderation_timestamp = timezone.now()

            # Handle the final action
            if final_action == 'Accept':
                post.save()
                messages.success(request, "Post created successfully.")
                return redirect('forum:post_detail', pk=post.pk)
            elif final_action == 'Issue Warning':
                # Increment user's warning count
                author.warning_count += 1
                author.save()

                post.save()

                # Inform the user
                warning_attributes = [
                    attr for attr, action in actions.items() if action == 'Issue Warning']
                messages.warning(

forum/templates/forum/admin/admin-panel.html
{% extends 'forum/base/base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    <title>Admin Panel</title>
{% endblock %}

{% block css %}

<link rel="stylesheet" href="{% static 'forum/css/home/home-page.css' %}">
<link rel="stylesheet" href="{% static 'forum/css/profile/profile-page.css' %}">
<link rel="stylesheet" href="{% static 'forum/css/admin/admin-panel.css' %}">

{% endblock %}

{% block main %}

  

  <main class="profile-section">
    <div class="content-wrapper">
      <div class="sidebar bg-light p-3">
        <h5>Admin Panel</h5>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link left-sidebar-link" href="{% url 'forum:home' %}">
              <i class="fa-solid fa-house fa-lg"></i> Home</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link left-sidebar-link" href="#"
              ><i class="fa-solid fa-fire fa-lg"></i> Popular</a
            >
          </li>
        </ul>
        <div class="profile-container">
          <h5 class="mt-3 mb-3">
            <i class="fa-solid fa-user fa-lg"></i> Profile
          </h5>
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link left-sidebar-link" href="#"
                ><i class="fa-solid fa-right-from-bracket fa-lg"></i>
                Logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="main-profile-section">
      <h3 class="mb-3 text-center">Welcome back user123!</h3>

      <div aria-live="polite" aria-atomic="true" class="d-flex justify-content-center align-items-center w-100">
        {% if messages %}
            {% for message in messages %}
            <div id="toastMessage" class="toast align-items-center text-light bg-dark border-0" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="60000">
                <div class="d-flex">
                    <div class="toast-body">
                    <!-- Display Django messages inside the toast -->
                    {{ message }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
            {% endfor %}
        {% endif %}
      </div>

      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item profile-nav-tab" role="presentation">
          <a
            class="nav-link active"
            id="simple-tab-0"
            data-bs-toggle="tab"
            href="#simple-tabpanel-0"
            role="tab"
            aria-controls="simple-tabpanel-0"
            aria-selected="true"
            >Overview</a
          >
        </li>
        <li class="nav-item profile-nav-tab" role="presentation">
          <a
            class="nav-link"
            id="simple-tab-1"
            data-bs-toggle="tab"
            href="#simple-tabpanel-1"
            role="tab"
            aria-controls="simple-tabpanel-1"
            aria-selected="false"
            >New Posts Today</a
          >
        </li>
        <li class="nav-item profile-nav-tab" role="presentation">
          <a
            class="nav-link"
            id="simple-tab-2"
            data-bs-toggle="tab"
            href="#simple-tabpanel-2"
            role="tab"
            aria-controls="simple-tabpanel-2"
            aria-selected="false"
            >Reported Posts</a
          >
        </li>
      </ul>
      <div class="tab-content pt-5" id="tab-content">
        <div
          class="tab-pane active"
          id="simple-tabpanel-0"
          role="tabpanel"
          aria-labelledby="simple-tab-0"
        >
          <div class="profile-tab overview-tab ms-3">
            <!-- Tab 1 -->
            <div class="container admin-overview-container">
              <div class="row align-items-start">
                <div class="col">
                  <h6 class="pb-2">Total posts</h6>
                  <h4 class="pb-2">{{post_count}}</h4>  
                </div>
                <div class="col vr-col">
                  <div
                    class="d-flex justify-content-center"
                    style="height: 100px"
                  >
                    <div class="vr"></div>
                  </div>
                </div>
                <div class="col">
                  <h6 class="pb-2">Total Reports</h6>
                  <h4 class="pb-2">{{reported_posts_count}}</h4>
                </div>
              </div>
            </div>
          </div>

          <!-- <div class="most-popular-post-container container ms-3">
          </div> -->
        </div>

        <div
          class="tab-pane"
          id="simple-tabpanel-1"
          role="tabpanel"
          aria-labelledby="simple-tab-1"
        >
          <!-- tab 2 -->
          <div class="post-tab-container new-posts-tab-container ms-3">
            {% if recent_posts %}

            <h4 class="mb-4">New Posts</h4>

            {% for post in recent_posts %}

              <div class="user-post-card card">
                <div class="card-body">

                  <div
                    class="card-title-container d-flex justify-content-between align-items-center mb-3"
                  >
                    <h5 class="card-title mb-0">
                      <a
                        class="user-post-link"
                        href=""
                      >
                        {{post.title}}
                      </a>
                    </h5>

                    <div class="d-flex align-items-center">
                      <p class="text-muted me-3 mb-0">{{post.time_created|naturaltime}}</p>
                    </div>
                  </div>

                  <!-- Community and Category -->
                  <div class="d-flex align-items-center custom-subtitle-container">
                    <h6 class="card-subtitle mb-0 text-body-secondary">{{ post.author.username }}</h6>
                  </div>
                  <!-- Community and Category -->
                  <div class="d-flex align-items-center custom-subtitle-container mt-2">
                    {% if post.community %}
                    <h6 class="card-subtitle mb-0 text-body-secondary"><a class="subtitle-link" href="{% url 'forum:community_page' post.community.id %}">{{ post.community }}</a></h6>
                    {% endif %}
                    {% if post.community and post.category %}
                    <h6 class="card-subtitle mb-0 text-body-secondary mx-2">-</h6>
                    {% endif %}
                    {% if post.category %}
                    <h6 class="card-subtitle mb-0 text-body-secondary">{{ post.category }}</h6>
                    {% endif %}
                    {% if post.poll %}
                    <h6 class="card-subtitle mb-0 text-body-secondary mx-2">-</h6>
                    <h6 class="card-subtitle mb-0 text-body-secondary">Poll</h6>
                    {% endif %}
                  </div>
                  <!-- Post Body -->
                  <p class="card-text mt-3">{{ post.body|truncatewords:20 }}</p>
                  <!-- Thumbnail -->
                  {% if post.image %}
                  <div class="container-fluid mt-5 thumbnail-container">
                    <img
                      src="{{ post.image.url }}"
                      alt="Thumbnail"
                      class="img-thumbnail"
                      data-bs-toggle="modal"
                      data-bs-target="#imageModal-{{ post.id }}"
                      style="cursor: pointer"
                    />
                  </div>
                  {% endif %}
              
                  <!-- Modal -->
                  {% if post.image %}
                  <div
                    class="modal modal-lg fade"
                    id="imageModal-{{ post.id }}"
                    tabindex="-1"
                    aria-labelledby="imageModalLabel"
                    aria-hidden="true"
                  >
                    <div class="modal-dialog modal-dialog-centered">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button
                            type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"
                          ></button>
                        </div>
                        <div class="modal-body">
                          <img
                            src="{{ post.image.url }}"
                            alt="Full-size Image"
                            class="img-fluid"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endif %}

                  <!-- Interaction Section -->
                  <p class="card-text mt-3">
                    <small class="text-muted"
                      >9 likes · 104 comments</small
                    >
                  </p>
                </div>
              </div>
              {% endfor %}

              {% else %}
              <h4 class="mb-4">No Recent Posts</h4>

            {% endif %}


            </div>


        </div>

        <div
          class="tab-pane"
          id="simple-tabpanel-2"
          role="tabpanel"
          aria-labelledby="simple-tab-2"
        >
          {% if reported_posts %}
          {% for post in reported_posts %}
            <div class="user-post-card card">
              <div class="card-body">
                <div
                  class="card-title-container d-flex justify-content-between align-items-center mb-3"
                >
                  <h5 class="card-title mb-0">
                    <a class="user-post-link" href="{% url 'forum:post_detail' post.id %}">
                      {{ post.title }}
                    </a>
                  </h5>
          
                  <div class="d-flex align-items-center">
                    <p class="text-muted me-3 mb-0">
                      {{ post.time_created|naturaltime }}
                    </p>
                  </div>
                </div>
        
                <!-- Subtitle -->
                <div class="d-flex align-items-center custom-subtitle-container mb-3">
                  {% if post.community %}
                  <h6 class="card-subtitle text-body-secondary me-1">
                    {{ post.community }}
                  </h6>
                  {% endif %}
                  {% if post.community and post.category %}
                  <h6 class="card-subtitle text-body-secondary">-</h6>
                  {% endif %}
                  {% if post.category %}
                  <h6 class="card-subtitle text-body-secondary ms-1">
                    {{ post.category }}
                  </h6>
                  {% endif %}
                </div>
        
                <!-- Post Body -->
                <p class="card-text">{{ post.body|truncatewords:20 }}</p>
        
                <!-- Thumbnail -->
                <div class="container-fluid">
                  {% if post.image %}
                  <img
                    src="{{ post.image.url }}"
                    alt="Thumbnail"
                    class="img-thumbnail"
                    data-bs-toggle="modal"
                    data-bs-target="#imageModal-{{ post.id }}"
                    style="cursor: pointer"
                  />
                  {% endif %}
                </div>
        
                <!-- Modal -->
                <div
                  class="modal modal-lg fade"
                  id="imageModal-{{ post.id }}"
                  tabindex="-1"
                  aria-labelledby="imageModalLabel"
                  aria-hidden="true"
                >
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button
                          type="button"
                          class="btn-close"
                          data-bs-dismiss="modal"
                          aria-label="Close"
                        ></button>
                      </div>
                      <div class="modal-body">
                        {% if post.image %}
                        <img
                          src="{{ post.image.url }}"
                          alt="Full-size Image"
                          class="img-fluid"
                        />
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
        
                <!-- Interaction Section -->
                <p class="card-text mt-3 d-flex justify-content-between align-items-center">
                  <small class="text-muted">
                    {{ post.total_likes }} likes · {{ post.comments.count }} comments · {{ post.report_count }} reports
                  </small>
                  <a href="{% url 'forum:view_reports' post.id %}" class="text-primary text-decoration-none ms-auto">
                    View reports
                  </a>
                </p>
              </div>
            </div>
          {% endfor %}
          {% else %}
            <p>No reported posts found.</p>
          {% endif %}
        
          </div>

      </div>
    </div>
  </main>

  <script>
      // Trigger toast if there are any messages
      document.addEventListener('DOMContentLoaded', function () {
        var toastEl = document.getElementById('toastMessage');
        var toast = new bootstrap.Toast(toastEl);
        {% if messages %}
          toast.show();
        {% endif %}
      });
  </script>

{% endblock %}